apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ref.fullname" . }}-migrate
  labels:
    {{- include "ref.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
stringData:
  {{- tpl (toYaml .Values.defaults.env) . | nindent 2 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ref.fullname" . }}-migrate
  labels:
    {{- include "ref.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "ref.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.defaults.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      containers:
      - name: migrate
        image: "{{ .Values.defaults.image.repository }}:{{ .Values.defaults.image.tag }}"
        imagePullPolicy: {{ .Values.defaults.image.pullPolicy }}
        command: ["ref", "db", "migrate"]
        {{- with .Values.defaults.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        envFrom:
        - secretRef:
            name: {{ include "ref.fullname" . }}-migrate
        {{- with .Values.defaults.volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.defaults.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
