{{- range $instance, $spec := (omit .Values.providers "defaults") -}}
{{- $spec := include "ref.providerSpec" (dict "root" $ "spec" $spec) | fromYaml -}}
{{- if $spec.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ref.fullname" $ }}-{{ $instance }}-config
  labels:
    app.kubernetes.io/component: {{ $instance }}
    {{- include "ref.labels" $ | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml $spec.config | nindent 4 }}
---
{{ end -}}
{{- end -}}
