{{- range $instance, $spec := (omit .Values.providers "defaults") -}}
{{- $spec := mergeOverwrite (deepCopy $.Values.defaults) $spec -}}
{{- $provider := $spec.provider | default $instance -}}
{{- if and (eq $provider "esmvaltool") $spec.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ref.fullname" $ }}-{{ $instance }}-config
  labels:
    app.kubernetes.io/component: {{ $instance }}
    {{- include "ref.labels" $ | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml $spec.config | nindent 4 }}
---
{{ end -}}
{{- end -}}
