{{- include "ref.validateOrchestrator" . -}}
{{- range $instance, $spec := (fromYaml (include "ref.workerInstances" .)) -}}
{{- $spec := include "ref.providerSpec" (dict "root" $ "spec" $spec) | fromYaml -}}
{{- if ($spec.autoscaling | default dict).enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "ref.fullname" $ }}-{{ $instance }}
  labels:
    app.kubernetes.io/component: {{ $instance }}
    {{- include "ref.labels" $ | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ref.fullname" $ }}-{{ $instance }}
  minReplicas: {{ $spec.autoscaling.minReplicas }}
  maxReplicas: {{ $spec.autoscaling.maxReplicas }}
  metrics:
  - type: Object
    object:
      metric:
        name: flower_task_prefetch_time_seconds
      describedObject:
        apiVersion: v1
        kind: Service
        name: celery-metrics-service # Service exposing Celery metrics
      target:
        type: Value
        value: "50" # Scale up if queue length exceeds 50
{{- end }}
---
{{ end -}}
