{{- range $provider, $spec := (omit .Values.providers "defaults") -}}
{{- $spec := include "ref.providerSpec" (dict "root" $ "spec" $spec) | fromYaml -}}
{{- include "ref.providerSecret" (dict "root" $ "provider" $provider "spec" $spec) }}
---
{{ end -}}
