{{- include "ref.validateOrchestrator" . -}}
{{- range $instance, $spec := (fromYaml (include "ref.workerInstances" .)) -}}
{{- $spec := include "ref.providerSpec" (dict "root" $ "spec" $spec) | fromYaml -}}
{{- include "ref.providerSecret" (dict "root" $ "provider" $instance "spec" $spec) }}
---
{{ end -}}
