{{- include "ref.validateOrchestrator" . -}}
{{- range $instance, $spec := (fromYaml (include "ref.workerInstances" .)) -}}
{{- $spec := include "ref.providerSpec" (dict "root" $ "spec" $spec) | fromYaml -}}
{{- if and $spec.serviceAccount $spec.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ref.serviceAccountName" (dict "root" $ "component" $instance "serviceAccount" $spec.serviceAccount) }}
  labels:
    app.kubernetes.io/component: {{ $instance }}
    {{- include "ref.labels" $ | nindent 4 }}
  {{- with $spec.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $spec.serviceAccount.automount }}
{{- end }}
---
{{ end -}}
