{{- range $instance, $spec := (omit .Values.providers "defaults") -}}
{{- $spec := mergeOverwrite (deepCopy $.Values.defaults) $spec -}}
{{- if and $spec.serviceAccount $spec.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $spec.serviceAccount.name | default (printf "%s-%s" (include "ref.fullname" $) $instance) }}
  labels:
    app.kubernetes.io/component: {{ $instance }}
    {{- include "ref.labels" $ | nindent 4 }}
  {{- with $spec.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $spec.serviceAccount.automount }}
{{- end }}
---
{{ end -}}
