{{- if .Values.api.enabled -}}
{{- include "ref.validateApiSecret" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ref.fullname" . }}-api
  labels:
    app.kubernetes.io/component: api
    {{- include "ref.labels" . | nindent 4 }}
stringData:
  {{- include "ref.instanceEnv" (dict "root" . "spec" .Values.api) | nindent 2 }}
{{- end }}
