apiVersion: v2
name: climate-ref-aft
description: A Helm chart for deploying the Climate REF application for the CMIP7 Assessment Fasttrack (AFT)
type: application

# Chart version tracks the AFT repo release version (SemVer)
version: 0.1.0

# Application version tracks the climate-ref core version
appVersion: "0.13.1"

dependencies:
- name: dragonfly
  version: v1.33.1
  repository: oci://ghcr.io/dragonflydb/dragonfly/helm
  condition: dragonfly.enabled
