apiVersion: v2
name: climate-ref-aft
description: A Helm chart for deploying the Climate REF application for the CMIP7 Assessment Fasttrack (AFT)
type: application

# autoscaling/v2 sets the floor.
kubeVersion: ">=1.23.0-0"

# Chart version tracks the AFT repo release version (SemVer)
version: 0.7.0

# Application version tracks the climate-ref core version
appVersion: "0.18.1"

dependencies:
- name: dragonfly
  version: v1.33.1
  repository: oci://ghcr.io/dragonflydb/dragonfly/helm
  condition: dragonfly.enabled
